// GENERATED CODE - DO NOT MODIFY BY HAND

const routesInfo = <Map<String, Object?>>[
  {
    'functionName': 'health',
    'method': 'get',
    'path': '/health',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Response',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Response',
    },
    'ignoreForClient': true,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'sendPasswordResetEmail',
    'method': 'post',
    'path': '/v1/auth/forgot-password',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'email',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'redirectTo',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'logout',
    'method': 'delete',
    'path': '/v1/auth/logout',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': true,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'refresh',
    'method': 'get',
    'path': '/v1/auth/refresh',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'AuthResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'AuthResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'resetPassword',
    'method': 'post',
    'path': '/v1/auth/reset-password',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'token',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'newPassword',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'signInWithEmailAndPassword',
    'method': 'post',
    'path': '/v1/auth/sign-in-email-password',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'email',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'password',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'AuthResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'AuthResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'signInWithIdToken',
    'method': 'post',
    'path': '/v1/auth/sign-in-with-id-token',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'provider',
        'typeName': 'IdTokenAuthProvider',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': true,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'idToken',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'nonce',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'AuthResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'AuthResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'signInWithOtp',
    'method': 'post',
    'path': '/v1/auth/sign-in-with-otp',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'email',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'user',
    'method': 'get',
    'path': '/v1/auth/user',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'User',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'User',
    },
    'ignoreForClient': false,
    'requiresAuth': true,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'verifyOtp',
    'method': 'post',
    'path': '/v1/auth/verify-otp',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'email',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'otp',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'AuthResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'AuthResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/buckets',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'List<Bucket>',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': true,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': 'Bucket',
      'innerTypeName': 'List<Bucket>',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'create',
    'method': 'post',
    'path': '/v1/collections',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'name',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'listRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'createRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'updateRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'deleteRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewQuery',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'type',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'attributes',
        'typeName': 'List<Attribute>?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'Attribute',
        'listItemIsMappable': true,
      },
      {
        'name': 'indexes',
        'typeName': 'List<Index>?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'Index',
        'listItemIsMappable': true,
      },
    ],
    'returnTypeName': 'Collection',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Collection',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/collections',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'limit',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '10',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'offset',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '0',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'List<Collection>',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': true,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': 'Collection',
      'innerTypeName': 'List<Collection>',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'export',
    'method': 'get',
    'path': '/v1/collections/export',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'ExportResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ExportResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'import',
    'method': 'post',
    'path': '/v1/collections/import',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'collections',
        'typeName': 'List<Map<String, dynamic>>',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'Map<String, dynamic>',
        'listItemIsMappable': false,
      },
      {
        'name': 'overwrite',
        'typeName': 'bool',
        'isOptional': true,
        'isNullable': false,
        'defaultValue': 'false',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'ImportResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ImportResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/logs',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'orderBy',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'filter',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'limit',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '10',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'offset',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '0',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'ListAppLogsResult',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ListAppLogsResult',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'subscribe',
    'method': 'get',
    'path': '/v1/realtime',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'channels',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'RealtimeEvent',
    'returnTypeFlags': <String, Object?>{
      'isStream': true,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'RealtimeEvent',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'get',
    'method': 'get',
    'path': '/v1/settings',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Settings',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Settings',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'update',
    'method': 'patch',
    'path': '/v1/settings',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'appName',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'siteUrl',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'redirectUrls',
        'typeName': 'List<String>?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'String',
        'listItemIsMappable': false,
      },
      {
        'name': 's3',
        'typeName': 'S3Settings?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': true,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'mail',
        'typeName': 'MailSettings?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': true,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'oauthProviders',
        'typeName': 'OAuthProviderList?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': true,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Settings',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Settings',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'generateAppleClientSecret',
    'method': 'post',
    'path': '/v1/settings/generate-apple-client-secret',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'clientId',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'teamId',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'keyId',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'privateKey',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'duration',
        'typeName': 'int',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'String',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': true,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'String',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'testS3Connection',
    'method': 'get',
    'path': '/v1/settings/s3',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'stats',
    'method': 'get',
    'path': '/v1/stats',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'DashboardStats',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'DashboardStats',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/users',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'orderBy',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'filter',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'limit',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '10',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'offset',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '0',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'ListUsersResult',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ListUsersResult',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'create',
    'method': 'post',
    'path': '/v1/users',
    'pathParams': <String>[],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'id',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'password',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'name',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'email',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'superUser',
        'typeName': 'bool',
        'isOptional': true,
        'isNullable': false,
        'defaultValue': 'false',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'User',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'User',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'oauth2',
    'method': 'post',
    'path': '/v1/auth/oauth2/<provider>',
    'pathParams': <String>['provider'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'redirectUrl',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'String',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': true,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'String',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'oauth2Callback',
    'method': 'get',
    'path': '/v1/auth/oauth2/<provider>/callback',
    'pathParams': <String>['provider'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Response',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Response',
    },
    'ignoreForClient': true,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'oauth2CallbackPost',
    'method': 'post',
    'path': '/v1/auth/oauth2/<provider>/callback',
    'pathParams': <String>['provider'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Response',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Response',
    },
    'ignoreForClient': true,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'create',
    'method': 'post',
    'path': '/v1/buckets/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'listRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'createRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'updateRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'deleteRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Bucket',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Bucket',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'delete',
    'method': 'delete',
    'path': '/v1/buckets/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'get',
    'method': 'get',
    'path': '/v1/buckets/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Bucket',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Bucket',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'update',
    'method': 'patch',
    'path': '/v1/buckets/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'newBucketName',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'listRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'createRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'updateRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'deleteRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Bucket',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Bucket',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'get',
    'method': 'get',
    'path': '/v1/collections/<collectionName>',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Collection',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Collection',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'delete',
    'method': 'delete',
    'path': '/v1/collections/<collectionName>',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'update',
    'method': 'patch',
    'path': '/v1/collections/<collectionName>',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'newCollectionName',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'attributes',
        'typeName': 'List<Attribute>?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'Attribute',
        'listItemIsMappable': true,
      },
      {
        'name': 'indexes',
        'typeName': 'List<Index>?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': true,
        'listItemTypeName': 'Index',
        'listItemIsMappable': true,
      },
      {
        'name': 'listRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'createRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'updateRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'deleteRule',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'viewQuery',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Collection',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Collection',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'generate',
    'method': 'post',
    'path': '/v1/collections/<collectionName>/generate',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'count',
        'typeName': 'int',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'GenerateResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'GenerateResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/documents/<collectionName>',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'orderBy',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'filter',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'limit',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '10',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'offset',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '0',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'ListDocumentsResult',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ListDocumentsResult',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'create',
    'method': 'post',
    'path': '/v1/documents/<collectionName>',
    'pathParams': <String>['collectionName'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'data',
        'typeName': 'Map<String, Object?>',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Document',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Document',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'get',
    'method': 'get',
    'path': '/v1/documents/<collectionName>/<documentId>',
    'pathParams': <String>['collectionName', 'documentId'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'Document',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Document',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'delete',
    'method': 'delete',
    'path': '/v1/documents/<collectionName>/<documentId>',
    'pathParams': <String>['collectionName', 'documentId'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'update',
    'method': 'patch',
    'path': '/v1/documents/<collectionName>/<documentId>',
    'pathParams': <String>['collectionName', 'documentId'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'data',
        'typeName': 'Map<String, Object?>',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'Document',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'Document',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'list',
    'method': 'get',
    'path': '/v1/files/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'path',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'orderBy',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'filter',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'limit',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '10',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'offset',
        'typeName': 'int?',
        'isOptional': true,
        'isNullable': true,
        'defaultValue': '0',
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'ListFilesResult',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'ListFilesResult',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'delete',
    'method': 'delete',
    'path': '/v1/files/<bucket>',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'path',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'move',
    'method': 'patch',
    'path': '/v1/files/<bucket>/<fileId>',
    'pathParams': <String>['bucket', 'fileId'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'destination',
        'typeName': 'String',
        'isOptional': false,
        'isNullable': false,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'File',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'File',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'download',
    'method': 'get',
    'path': '/v1/files/<bucket>/<fileId>',
    'pathParams': <String>['bucket', 'fileId'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'token',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'FileResponse',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': true,
      'listItemTypeName': null,
      'innerTypeName': 'FileResponse',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'getDownloadUrl',
    'method': 'get',
    'path': '/v1/files/<bucket>/<fileId>/url',
    'pathParams': <String>['bucket', 'fileId'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'GetDownloadUrlResult',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'GetDownloadUrlResult',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'upload',
    'method': 'post',
    'path': '/v1/files/<bucket>/upload',
    'pathParams': <String>['bucket'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'File',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'File',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'delete',
    'method': 'delete',
    'path': '/v1/users/<userId>',
    'pathParams': <String>['userId'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'void',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': true,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'void',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
  {
    'functionName': 'get',
    'method': 'get',
    'path': '/v1/users/<userId>',
    'pathParams': <String>['userId'],
    'bodyParams': <Map<String, Object?>>[
    ],
    'returnTypeName': 'User',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'User',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': false,
  },
  {
    'functionName': 'update',
    'method': 'patch',
    'path': '/v1/users/<userId>',
    'pathParams': <String>['userId'],
    'bodyParams': <Map<String, Object?>>[
      {
        'name': 'email',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'password',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'name',
        'typeName': 'String?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
      {
        'name': 'superUser',
        'typeName': 'bool?',
        'isOptional': false,
        'isNullable': true,
        'defaultValue': null,
        'isEnum': false,
        'isDateTime': false,
        'isMappable': false,
        'isList': false,
        'listItemTypeName': null,
        'listItemIsMappable': false,
      },
    ],
    'returnTypeName': 'User',
    'returnTypeFlags': <String, Object?>{
      'isStream': false,
      'isList': false,
      'isBool': false,
      'isString': false,
      'isNum': false,
      'isMap': false,
      'isVoid': false,
      'isFileResponse': false,
      'listItemTypeName': null,
      'innerTypeName': 'User',
    },
    'ignoreForClient': false,
    'requiresAuth': false,
    'requiresSuperUserAuth': true,
  },
];
